<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsvpeke\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsvpeke/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMsvpeke.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMsvpeke\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMsvpeke\appProdProjectContainer([
    'container.build_hash' => 'Msvpeke',
    'container.build_id' => '898998c1',
    'container.build_time' => 1638731469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMsvpeke');
